### PR TITLE
Absorb upstream changes up to v0.27-beta

### PR DESCRIPTION
**Pull request by MattWellie**
Context: https://centrepopgen.slack.com/archives/C02E83V5JSF/p1678910500913689?thread_ts=1678841985.740089&cid=C02E83V5JSF

Prior to continuing adoption work we've been advised to adopt changes up until the v0.27b release (c. 12 hours ago)

I've not done a downstream merge on a forked repo before 😬 Hoping this is the right process

### CODE REVIEW

**Review by illusional — APPROVED** [review]
This way is fine, given there are no conflicts (which I'm surprised at).
Otherwise you could generally run in a local copy:

```bash
git remote add upstream <upstream-remote>
git checkout -b merge-from-upstream
git pull upstream main
# resolve conflicts if there any
git push
```

**Comment by MattWellie** [comment]
I expected way more conflicts, so this seemed too good to be true.. I'll bear that in mind for future changes!

**Comment by lgruen** [comment]
Can this be closed, now that https://github.com/populationgenomics/gatk-sv/pull/12 has been merged?

**Comment by MattWellie** [comment]
Closed - see #12

**Pull request closed without merging**
